name: Claude Security Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  security-review:
    runs-on: ubuntu-latest
    steps:
      - name: Claude Security Review
        uses: anthropics/claude-code-security-review@main
        with:
          anthropic_api_key: ${{ secrets.CLAUDE_API_KEY }}
          # Configure for financial/enterprise systems
          severity_threshold: "medium"
          include_patterns: "**/*.{js,ts,py,sql,java,go,rs,php,rb,cs}"
          exclude_patterns: "node_modules/**,*.test.*,*.spec.*,.DS_Store/**"